package college.netbeans.quizmini;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choices1 = new javax.swing.ButtonGroup();
        choices2 = new javax.swing.ButtonGroup();
        choices3 = new javax.swing.ButtonGroup();
        choices4 = new javax.swing.ButtonGroup();
        choices5 = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        q1c1 = new javax.swing.JRadioButton();
        q1c2 = new javax.swing.JRadioButton();
        q1c3 = new javax.swing.JRadioButton();
        q1c4 = new javax.swing.JRadioButton();
        q2c1 = new javax.swing.JRadioButton();
        q2c3 = new javax.swing.JRadioButton();
        q2c2 = new javax.swing.JRadioButton();
        q2c4 = new javax.swing.JRadioButton();
        question2 = new javax.swing.JLabel();
        q4c2 = new javax.swing.JRadioButton();
        q4c4 = new javax.swing.JRadioButton();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        q3c1 = new javax.swing.JRadioButton();
        q3c2 = new javax.swing.JRadioButton();
        q3c3 = new javax.swing.JRadioButton();
        q3c4 = new javax.swing.JRadioButton();
        q4c1 = new javax.swing.JRadioButton();
        q4c3 = new javax.swing.JRadioButton();
        q5c3 = new javax.swing.JRadioButton();
        q5c2 = new javax.swing.JRadioButton();
        q5c4 = new javax.swing.JRadioButton();
        question5 = new javax.swing.JLabel();
        q5c1 = new javax.swing.JRadioButton();
        SUBMIT = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        label_score = new javax.swing.JLabel();
        remark = new javax.swing.JLabel();
        score_count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.Color.yellow);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        container.setBackground(new java.awt.Color(32, 29, 48));
        container.setForeground(new java.awt.Color(224, 204, 143));

        title.setBackground(new java.awt.Color(36, 31, 54));
        title.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        title.setForeground(new java.awt.Color(229, 229, 229));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("QUIZMINI");

        question1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        question1.setForeground(new java.awt.Color(229, 229, 229));
        question1.setText("1. How many day in one week?");

        q1c1.setBackground(new java.awt.Color(32, 29, 48));
        choices1.add(q1c1);
        q1c1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q1c1.setForeground(new java.awt.Color(229, 229, 229));
        q1c1.setText("four days");
        q1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1c1ActionPerformed(evt);
            }
        });

        q1c2.setBackground(new java.awt.Color(32, 29, 48));
        choices1.add(q1c2);
        q1c2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q1c2.setForeground(new java.awt.Color(229, 229, 229));
        q1c2.setText("six days");
        q1c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1c2ActionPerformed(evt);
            }
        });

        q1c3.setBackground(new java.awt.Color(32, 29, 48));
        choices1.add(q1c3);
        q1c3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q1c3.setForeground(new java.awt.Color(229, 229, 229));
        q1c3.setText("five days");
        q1c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1c3ActionPerformed(evt);
            }
        });

        q1c4.setBackground(new java.awt.Color(32, 29, 48));
        choices1.add(q1c4);
        q1c4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q1c4.setForeground(new java.awt.Color(229, 229, 229));
        q1c4.setText("seven days");
        q1c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1c4ActionPerformed(evt);
            }
        });

        q2c1.setBackground(new java.awt.Color(32, 29, 48));
        choices2.add(q2c1);
        q2c1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q2c1.setForeground(new java.awt.Color(229, 229, 229));
        q2c1.setText("Venus");
        q2c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2c1ActionPerformed(evt);
            }
        });

        q2c3.setBackground(new java.awt.Color(32, 29, 48));
        choices2.add(q2c3);
        q2c3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q2c3.setForeground(new java.awt.Color(229, 229, 229));
        q2c3.setText("Mars");
        q2c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2c3ActionPerformed(evt);
            }
        });

        q2c2.setBackground(new java.awt.Color(32, 29, 48));
        choices2.add(q2c2);
        q2c2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q2c2.setForeground(new java.awt.Color(229, 229, 229));
        q2c2.setText("Earth");
        q2c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2c2ActionPerformed(evt);
            }
        });

        q2c4.setBackground(new java.awt.Color(32, 29, 48));
        choices2.add(q2c4);
        q2c4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q2c4.setForeground(new java.awt.Color(229, 229, 229));
        q2c4.setText("Jupiter");
        q2c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2c4ActionPerformed(evt);
            }
        });

        question2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        question2.setForeground(new java.awt.Color(229, 229, 229));
        question2.setText("2. What is the red planet closest to Earth?");

        q4c2.setBackground(new java.awt.Color(32, 29, 48));
        choices4.add(q4c2);
        q4c2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q4c2.setForeground(new java.awt.Color(229, 229, 229));
        q4c2.setText("Twigs");
        q4c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4c2ActionPerformed(evt);
            }
        });

        q4c4.setBackground(new java.awt.Color(32, 29, 48));
        choices4.add(q4c4);
        q4c4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q4c4.setForeground(new java.awt.Color(229, 229, 229));
        q4c4.setText("Roots");
        q4c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4c4ActionPerformed(evt);
            }
        });

        question3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        question3.setForeground(new java.awt.Color(229, 229, 229));
        question3.setText("4. What part of Tree that holds the earth?");

        question4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        question4.setForeground(new java.awt.Color(229, 229, 229));
        question4.setText("3. In what Universe are we?");

        q3c1.setBackground(new java.awt.Color(32, 29, 48));
        choices3.add(q3c1);
        q3c1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q3c1.setForeground(new java.awt.Color(229, 229, 229));
        q3c1.setText("Milky way");
        q3c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3c1ActionPerformed(evt);
            }
        });

        q3c2.setBackground(new java.awt.Color(32, 29, 48));
        choices3.add(q3c2);
        q3c2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q3c2.setForeground(new java.awt.Color(229, 229, 229));
        q3c2.setText("Philippines");
        q3c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3c2ActionPerformed(evt);
            }
        });

        q3c3.setBackground(new java.awt.Color(32, 29, 48));
        choices3.add(q3c3);
        q3c3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q3c3.setForeground(new java.awt.Color(229, 229, 229));
        q3c3.setText("Andromeda");
        q3c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3c3ActionPerformed(evt);
            }
        });

        q3c4.setBackground(new java.awt.Color(32, 29, 48));
        choices3.add(q3c4);
        q3c4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q3c4.setForeground(new java.awt.Color(229, 229, 229));
        q3c4.setText("World");
        q3c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3c4ActionPerformed(evt);
            }
        });

        q4c1.setBackground(new java.awt.Color(32, 29, 48));
        choices4.add(q4c1);
        q4c1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q4c1.setForeground(new java.awt.Color(229, 229, 229));
        q4c1.setText("Leaves");
        q4c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4c1ActionPerformed(evt);
            }
        });

        q4c3.setBackground(new java.awt.Color(32, 29, 48));
        choices4.add(q4c3);
        q4c3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q4c3.setForeground(new java.awt.Color(229, 229, 229));
        q4c3.setText("Trunk");
        q4c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4c3ActionPerformed(evt);
            }
        });

        q5c3.setBackground(new java.awt.Color(32, 29, 48));
        choices5.add(q5c3);
        q5c3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q5c3.setForeground(new java.awt.Color(229, 229, 229));
        q5c3.setText("Seven");
        q5c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5c3ActionPerformed(evt);
            }
        });

        q5c2.setBackground(new java.awt.Color(32, 29, 48));
        choices5.add(q5c2);
        q5c2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q5c2.setForeground(new java.awt.Color(229, 229, 229));
        q5c2.setText("Eight");
        q5c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5c2ActionPerformed(evt);
            }
        });

        q5c4.setBackground(new java.awt.Color(32, 29, 48));
        choices5.add(q5c4);
        q5c4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q5c4.setForeground(new java.awt.Color(229, 229, 229));
        q5c4.setText("Nine");
        q5c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5c4ActionPerformed(evt);
            }
        });

        question5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        question5.setForeground(new java.awt.Color(229, 229, 229));
        question5.setText("5.  (2 x 2) + 2?");

        q5c1.setBackground(new java.awt.Color(32, 29, 48));
        choices5.add(q5c1);
        q5c1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        q5c1.setForeground(new java.awt.Color(229, 229, 229));
        q5c1.setText("Six");
        q5c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5c1ActionPerformed(evt);
            }
        });

        SUBMIT.setBackground(new java.awt.Color(229, 229, 229));
        SUBMIT.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SUBMIT.setForeground(new java.awt.Color(32, 29, 48));
        SUBMIT.setText("START");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });

        RESET.setBackground(new java.awt.Color(229, 229, 229));
        RESET.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        RESET.setForeground(new java.awt.Color(32, 29, 48));
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        label_score.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_score.setForeground(new java.awt.Color(229, 229, 229));
        label_score.setText("Score:");

        remark.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        remark.setForeground(new java.awt.Color(229, 229, 229));
        remark.setText("REMARK");

        score_count.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        score_count.setForeground(new java.awt.Color(229, 229, 229));
        score_count.setText("0");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(question4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2c1)
                                    .addComponent(q2c3))
                                .addGap(186, 186, 186)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2c2)
                                    .addComponent(q2c4))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q1c3)
                                    .addComponent(q1c1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q1c4)
                                    .addComponent(q1c2)))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q3c1)
                                    .addComponent(q3c3)
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q4c3)
                                            .addComponent(q4c1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q3c4)
                                    .addComponent(q3c2)
                                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(q4c2)
                                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q5c2)
                                            .addComponent(q4c4)
                                            .addComponent(q5c4)))))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(RESET)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SUBMIT))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question5)
                                    .addComponent(question3))
                                .addGap(117, 117, 117))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5c1)
                            .addComponent(q5c3))
                        .addGap(3, 272, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(question2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(question1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score_count)
                .addGap(32, 32, 32))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(label_score))
                            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(title)
                                .addComponent(score_count))))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(remark)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1c1)
                    .addComponent(q1c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1c4)
                    .addComponent(q1c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2c1)
                    .addComponent(q2c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2c4)
                    .addComponent(q2c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3c1)
                    .addComponent(q3c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3c4)
                    .addComponent(q3c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4c1)
                    .addComponent(q4c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4c4)
                    .addComponent(q4c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5c1)
                    .addComponent(q5c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5c4)
                    .addComponent(q5c3))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SUBMIT)
                    .addComponent(RESET))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1c1ActionPerformed

    private void q1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1c2ActionPerformed

    private void q1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1c3ActionPerformed

    private void q1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1c4ActionPerformed

    private void q2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2c1ActionPerformed

    private void q2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2c3ActionPerformed

    private void q2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2c2ActionPerformed

    private void q2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2c4ActionPerformed

    private void q4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4c2ActionPerformed

    private void q4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4c4ActionPerformed

    private void q3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3c1ActionPerformed

    private void q3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3c2ActionPerformed

    private void q3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3c3ActionPerformed

    private void q3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3c4ActionPerformed

    private void q4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4c1ActionPerformed

    private void q4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4c3ActionPerformed

    private void q5c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5c3ActionPerformed

    private void q5c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5c2ActionPerformed

    private void q5c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5c4ActionPerformed

    private void q5c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5c1ActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        // TODO add your handling code here:
        int score = 0;
        int ctr = 0;
        if(q1c1.isSelected() || q1c2.isSelected() || q1c3.isSelected() || q1c4.isSelected()){
            ctr++;
        }
        if(q2c1.isSelected() || q2c2.isSelected() || q2c3.isSelected() || q2c4.isSelected()){
            ctr++;
        }
        if(q3c1.isSelected() || q3c2.isSelected() || q3c3.isSelected() || q3c4.isSelected()){
            ctr++;
        }
        if(q4c1.isSelected() || q4c2.isSelected() || q4c3.isSelected() || q4c4.isSelected()){
            ctr++;
        }
        if(q5c1.isSelected() || q5c2.isSelected() || q5c3.isSelected() || q5c4.isSelected()){
            ctr++;
        }
        if(ctr == 5){
            if(q1c4.isSelected()){
            score += 1;
            question1.setForeground(Color.green);
            } else {
            question1.setForeground(Color.red);
            }
            if(q2c3.isSelected()){
            score += 1;
            question2.setForeground(Color.green);
            } else {
            question2.setForeground(Color.red);
            }
            if(q3c1.isSelected()){
            score += 1;
            question3.setForeground(Color.green);
            } else {
            question3.setForeground(Color.red);
            }
            if(q4c4.isSelected()){
            score += 1;
            question4.setForeground(Color.green);
            } else {
            question4.setForeground(Color.red);
            }
            if(q5c2.isSelected()){
            score += 1;
            question5.setForeground(Color.green);
            } else {
            question5.setForeground(Color.red);
            }
            score_count.setText(String.valueOf(score));
            SUBMIT.setEnabled(false);
        }
        if(score < 3){
            remark.setText("FAILURE");
        } else if(score == 5){
            remark.setText("VERY GOOD");
        } else {
            remark.setText("PASS");
        }
    }//GEN-LAST:event_SUBMITActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        SUBMIT.setEnabled(true);
        score_count.setText("0");
        choices1.clearSelection();
        choices2.clearSelection();
        choices3.clearSelection();
        choices4.clearSelection();
        choices5.clearSelection();
        question1.setForeground(new Color(229, 229, 229));
        question2.setForeground(new Color(229, 229, 229));
        question3.setForeground(new Color(229, 229, 229));
        question4.setForeground(new Color(229, 229, 229));
        question5.setForeground(new Color(229, 229, 229));
        remark.setText("REMARK");
    }//GEN-LAST:event_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RESET;
    private javax.swing.JButton SUBMIT;
    private javax.swing.ButtonGroup choices1;
    private javax.swing.ButtonGroup choices2;
    private javax.swing.ButtonGroup choices3;
    private javax.swing.ButtonGroup choices4;
    private javax.swing.ButtonGroup choices5;
    private javax.swing.JPanel container;
    private javax.swing.JLabel label_score;
    private javax.swing.JRadioButton q1c1;
    private javax.swing.JRadioButton q1c2;
    private javax.swing.JRadioButton q1c3;
    private javax.swing.JRadioButton q1c4;
    private javax.swing.JRadioButton q2c1;
    private javax.swing.JRadioButton q2c2;
    private javax.swing.JRadioButton q2c3;
    private javax.swing.JRadioButton q2c4;
    private javax.swing.JRadioButton q3c1;
    private javax.swing.JRadioButton q3c2;
    private javax.swing.JRadioButton q3c3;
    private javax.swing.JRadioButton q3c4;
    private javax.swing.JRadioButton q4c1;
    private javax.swing.JRadioButton q4c2;
    private javax.swing.JRadioButton q4c3;
    private javax.swing.JRadioButton q4c4;
    private javax.swing.JRadioButton q5c1;
    private javax.swing.JRadioButton q5c2;
    private javax.swing.JRadioButton q5c3;
    private javax.swing.JRadioButton q5c4;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel remark;
    private javax.swing.JLabel score_count;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
